### ISSUE TITLE
containsLocation API

### ISSUE THREAD

**Issue by saifuddin** [zilverline/google-maps#23]
Hi,

I'm trying to find out if a point is inside a polygon. The polygon is an array of coordinates that i've already defined. Basically I'm looking something like this:

https://developers.google.com/maps/documentation/javascript/examples/poly-containsLocation

Do you know if this gem can do it? Thanks!

**Comment by Ruben-Hartog** [comment]
Hi @saifuddin ,

Unfortunately this is not yet supported by this gem.
